timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/arikkfir/secrets/github-accesstoken/versions/latest
      env: GITHUB_TOKEN
    - versionName: projects/arikkfir/secrets/github-ssh-key/versions/latest
      env: GITHUB_SSH_KEY
steps:
  - name: hashicorp/terraform:0.14.5
    args: [init]
  - name: hashicorp/terraform:0.14.5
    args: [apply, -input=false, -lock-timeout=180s, -auto-approve]
  - name: hashicorp/terraform:0.14.5
    entrypoint: sh
    args: ['-euxc', 'terraform output -json > tf-outputs.json']
  - name: kroniak/ssh-client
    entrypoint: bash
    dir: /root/.ssh
    args:
      - -euc
      - echo "$${GITHUB_SSH_KEY}" > id_rsa && chmod 600 id_rsa && ssh-keyscan -t rsa github.com > known_hosts
    secretEnv: [GITHUB_SSH_KEY]
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: alpine/git
    args: [clone, git@github.com:arikkfir/infrastructure.git, '--branch=${BRANCH_NAME}', clone]
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: mikefarah/yq
    dir: clone/kubernetes/traefik
    entrypoint: sh
    args:
      - -euc
      - yq e -i ".spec.values.service.loadBalancerIP = \"$$(yq e '.gke_ingress_external_ip.value' ../../../outputs.json)\"" traefik.yaml
  - name: alpine/git
    dir: clone
    args: [add, .]
  - name: alpine/git
    dir: clone
    entrypoint: sh
    args: ['-euc', 'git diff-index --quiet HEAD || git commit -m "Update infrastructure"']
    env:
      - GIT_COMMITTER_EMAIL=arik@kfirs.com
      - GIT_AUTHOR_EMAIL=arik@kfirs.com
  - name: alpine/git
    dir: clone
    args: [push]
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/kaniko-project/executor:latest
    args: ['--destination=gcr.io/${PROJECT_ID}/${REPO_NAME}/flux:${COMMIT_SHA}', '--cache=true', '--context=./tools/flux']
  - name: gcr.io/${PROJECT_ID}/${REPO_NAME}/flux:${COMMIT_SHA}
    entrypoint: bash
    args:
      - -euxc
      - |-
        gcloud container clusters get-credentials --zone=europe-west3-a primary
        if [[ "$$(kubectl get namespaces | grep -c flux-system)" == "0" ]]; then
          flux bootstrap github --personal \
                                --owner=arikkfir \
                                --repository=${REPO_NAME} \
                                --branch=${BRANCH_NAME} \
                                --path=kubernetes \
                                --namespace=flux-system
        fi
        flux create kustomization global --source=GitRepository/flux-system \
                                         --path=kubernetes/global \
                                         --prune \
                                         --interval=5m \
                                         --validation=client
    secretEnv: [GITHUB_TOKEN]
