apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    app: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
    component: master
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: master
  labels:
    app: jenkins
    component: master
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: jnlp
      port: 50000
      targetPort: jnlp
  selector:
    app: jenkins
    component: master
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
spec:
  secretName: jenkins-crt
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: jenkins.kfirs.com
  dnsNames:
    - jenkins.kfirs.com
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - jenkins.kfirs.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/whitelist-source-range: "${WHITELISTED_IP_CIDRS}"
spec:
  rules:
    - host: jenkins.kfirs.com
      http:
        paths:
          - backend:
              serviceName: master
              servicePort: http
  tls:
    - hosts:
        - jenkins.kfirs.com
      secretName: jenkins-crt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: master
  labels:
    app: jenkins
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      component: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        component: master
    spec:
      serviceAccountName: jenkins
      initContainers:
        - name: init-chown-data
          image: busybox:latest
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 64Mi
          command: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
          volumeMounts:
            - name: storage
              mountPath: /var/jenkins_home
              readOnly: false
      containers:
        - name: jenkins
          image: gcr.io/arikkfir/jenkins-master:0.0.1
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
          volumeMounts:
            - name: storage
              mountPath: /var/jenkins_home
              readOnly: false
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: jenkins
            readOnly: false
---
