apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker
  labels:
    app: spinnaker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: spinnaker
  name: spinnaker
  labels:
    app: spinnaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - namespace: spinnaker
    kind: ServiceAccount
    name: spinnaker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spinnaker
  name: halyard
  labels:
    app: spinnaker
    component: halyard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  namespace: spinnaker
  name: secrets
  labels:
    app: spinnaker
type: Opaque
data:
  jenkins-password: NTMxMTRkYzE0MTg2MTM4OTkwYWE4ZTZlNWZlZmFhOTg=
  spinnaker-gcr-account.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYXJpa2tmaXIiLAogICJwcml2YXRlX2tleV9pZCI6ICIxNDA2NTA5YWI0MzEwMzM1M2Y1NWJiODU1ZWRmMDc2MmFmMjhjMjU1IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUNrS3dhMUtHeHE0M2NSXG4wRDVLY0g4SWpjV1B5MEIwWGlaWkhZVHRDbXZubXBmdlpYY0xEMVFIQ01USmtsZUt4d2poRGVtMTFSbHpPeHdFXG53cXljZWNWL0JmemZLdmZtQUp2MjdrMDhVc0NCalVvV25CcmxmdlZIYU1LUExNanpEWnp5UUMwbm5SVEtNKy9OXG5DTGQxNjMybGtVTUhqa3NqeEx1ZndHbFZBSUpWQ3FqSmdBVkVWSklzUEthVmY4TDF1ekgwNFpCbFRxYXhLZUJRXG5uMGpsWDMyVGIvOVhDUjl4TERERlhmRmNJdDcyaGlLdkRMck4vU0ZNSjZkTm4wbjRGRXZxNUVRcFM4RHB6RjJHXG5KZ0Z3NUZUb2FQNEEzL29Rdy9tMjE3YmpWNmE5d3MwWEk5Yy9ZOG9PUTRFWk5rekZ5UHpQSlQyMjV1eWxGcG91XG52U0o0Z0pKcEFnTUJBQUVDZ2dFQUNUYlBySkZLbHl2bktKMGdoenNOMWpsbTBrTHlmaXJlbjNmVVdITG5vRENCXG5hejFZVTNXV2MyMUprT3EyeTh6a3NhK3A0Mlp2aEQ2Q3ZHaFV4SCtOTElEMTNXeTRUSW9uakNkNTRaM2ZaM3RrXG45M25tMmVTb292Wm44bk5DdFdtWkw5RHNUVGM0SXlxTHdMS2NOc1p6TkpJVTlMS2NMYk50WXgwQWpIWE5NRFZPXG54d3B0cFdCZk8wT2kvbytiWGFGSURzWmpBREU2bk92WmhZRXpVRnpEdlVnYnpTVUdYVEtRbktHdTBqM3ZTdzRzXG44L1ZaZTlhT2V1ZEZlTzgrV3NDTU02d0E1TVVTWnh0bW8wMDk1VWw0VFl2c0V3UkFUN1l6WGlUOVJHTmNpeWhwXG5mVjFmcDFsTlNaMWhsN3BjVDVhWGZETDM2blVlaFFWUjNSbFNkQjFaWlFLQmdRRG1weFVZY01hQU1Mb0VqNnV4XG5oRHprOTZhR3ZWRWR3Y2dkWTg4SlFJVDNaTGJZd3Myd3FaTmQwODVPU2tpb0pUdHNlL3k1T1FseDlsSzhWZXEwXG45SUk5R081U2Nqbm90TmVCL3JZbEQxbEJSWXVTOHNLaFFCZXRXc05EaktzNVdXMHM2bmttQVRFNVVtZndOeUdIXG5WM1ArRnB5OExWaUcwNUp3L2lCY2N4cnlzd0tCZ1FDMk5ZcmVYU1YrWHJIZS83dEwreHhVakZCVHBNWGUvaHFzXG5IbnArcnNFTGJ4QjlJOGFqSDhmdVdkMjNXYzhvUzdQODRKSEFDQ2VteWcxbmZDcnlMbHNzSnNqc0VnTUlHYVJPXG5NdUtpcGdZeTNGditvSytYMzFLRFVTeTcvcGNFKzk5enBlbnVhaU9zZkVyaUVseC80bHRHM0YzL1lvNXlHcWFBXG4ya2E4bUZwRWN3S0JnR0t2U2c5UzhSc1h2ZjhGbVdneU0vdWpHZFM4VzJCbjhMN2lYVXFRR0ZQZyszcHlucDdmXG5idlhPRVk3ZHFZaUhwWTBjMzF4QVV4STNXZDdLdzhqNGRHQy9zZmdFZDFKaFRYT0pEMVY3NDZ4Um5RNGFYN3V1XG5PSE1yU2pBMGwyM0tIVFFDZmlNTWo0cisvd21BRFJCakVuVzhKd004UTR3c0taTytwd25uRmJpUkFvR0JBSkFUXG5SRXhSNE96TW1kOFgzWlRWNlcvZFIwTHNYbDNXRldjVjdvd3ZTSXZ1OVYzT0pTb2xYaVRWUUdEVGpkOXlCTThuXG5EM2lGdWp6RE5kZ25NWm93RjMyUTZYenBQU1p4aUI4aFUxMkM1QkhoZG9pZnJGanRpRVEzc3FTd1NkL3gvWjFuXG5pdE12Y0NmYVhDZm9sdVcwS2JLZFcySXVIeTZRYmlvaTdwMy81aGlMQW9HQVVDQ2VYckFYSkNCcHF0aFZ0YmpoXG5mQTY2bGxHaFV6TjFxajVNRGN5REJZMGJTUDB0cCtpWDNEN2ZkMWVGNGJYeUJZcVQrVldkRVNrcWprVHpjaDBkXG4zR211MW9LbUNONDNuZXZMQVl2TnUrNXYwQ2pBZWtnVzlJaEtZZllJaDU1MkZmSkZQb3lJT01nWjEvQ05BU2VKXG5oaUJDbi9CTjM0ZEs0SzlHS0gxUkFpTT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJzcGlubmFrZXItZ2NyLWFjY291bnRAYXJpa2tmaXIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEzOTAyMzA2NDQ2MjIwMDA2MTkyIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zcGlubmFrZXItZ2NyLWFjY291bnQlNDBhcmlra2Zpci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
  spinnaker-gcs-account.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYXJpa2tmaXIiLAogICJwcml2YXRlX2tleV9pZCI6ICJlZGE0NTE2ZThlOGIzMTU0ZmYxNDRjNDkzNDBkYTYzYTNjZTExOGRjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUM0RzB5T0I3SC9DczZCXG5rSTFGbEJBdnVURGdxb1loQjFPQVZvRWUwT1ltWjduT29rMi9JSTY5RG5OQ0t6UlVCNHlFWkRFYXFPT3dNU1hVXG5tNkFXeWdwTklOMlo1czgxVHpYTE1uQTNFOXdYTnJMdS85b2IwUTk3Y00rVmxWbEYyQWNucVBUR01UVFZtR3k0XG52TUpvZ0FLdGh4dFgxQ3JZUUJVL2t5NEIxZEpUTlNmcExibjFSditGVC9rVVlIUlZHYy9sSmo3TnJLdVM1a3pWXG5EUDRqSXlIczBFUHhLVzZ6blpzSWhwbDl2NUVURW5CM3FrNkpwa2U3VmJHQkhOQSszSVhHOFEzYnBjL1lDZUhXXG52NU0yMDQ5VnNkSUM3NEJUTzRSYlZMbzdvRWlWUTA2dkUzbkpwbERTYXNBcEprbHpVQ1h5WWhPTUZobjFYWW9QXG5DTnhCaUhUUkFnTUJBQUVDZ2dFQVNiY0FmWVBlUkppT203a0ZuNXpMcUZnVmxuY2drbHZ0RnA5TVBzcjB3OTdYXG5Pa0dwTUlRNE1zRjA2OE1CeGoxcGlWN1dmRzZ3RDgxMThMMUpLYWJHM2gveEtweU1UYk9EL2ZLWmxLdjZmVDcxXG5BUlhuUGlrRWNtLzJaZFd4TTNKdVZ2WmkzM0kzVGVpa2E0bUVxN1BKbnJKUWcrZWJLZy9xa2hSN29OZDh5Yng0XG5LMmdBZERKbk9ZVlRTK0lwTm15a2xXbDJsZTY2T2J2WDlUYU9LS1ZxbEphQkk3NVRhR2U1NFNWT2cvS2ZPTWhuXG5CRFFzZS9NNnRRajNaQ29xS2s5S2ZUQVU3a05wNERidWJYMzFudkVWejNuRmNsZkJnK1NkOWFyTEV5NW1aamhIXG5OZ3NGVmpWWHRkRWllTzRLQytmdjR0MUVidUNpbGg3aTBnVHJwOWdiV3dLQmdRRC9wTDJTU1lFSWNLSk01TEdxXG5sWW9URnMyYXU0WFczQTV3VUU4bXVTU203bkRiTCtjSkVmS2N5WXM4cWluVElNc3YvaWdsM1duT3RwRTlIazRSXG53dkYxOEZWSU5QRFc2RDdWSFZSaE5Qb29mREpvMXBnUTNTYUhKTTJOMzJrTnZxWnVMbnZpUGE5c1BEdFF0NkRjXG5tSHYyTVA3VEl4dlgyaFFjWlpIZ002TjV5d0tCZ1FDNFhRVjE5eEloWFJkWE5kSFVrNWFPakQvZTQrdVU2N00zXG5ZVERlcW1SZzlIKzJzOFdyeXpVU0Z6NkdqaEFlVkxNYS9JeEluMGg5ai9MTHdqWEpwU01xU3F0RGFBcVZoSkFjXG40LzFnZDBFMlFucnl3VDA2UHdYeEtxTlNWSm43dDJiamI0cWJxQmdHV0c2UUlVZFpQSGRYY0lUNjBkcGJVL2dNXG56U1BLRW5qb1V3S0JnQjJWVXRxNjV0T3pOUlR3NGg1N2I1OEY1SVVqYmptTy9aekJybWNzeGJFTHBzTzJwMlhGXG5UZTRXNUtZQWl4YURsUC9ZeVl5WU1zWlpHaldZYkRCaC9zOUhJSmRhaVFSVm0rL05sUllxcTBoRUZ4Rkt4QTR2XG5pV1hhUEc5T2l6bXI5bGFKeW94RDF5a1BUMDNuOGhXVkQ4Tk5xQytHd0pJYUNubSt4MExLdHdCQkFvR0FQSzNSXG5HRXhqV1R2TWJOVzM1Q0ZYVWo5eTNpZGg2RGZUV296UWl0akdCT3MwQmF3UmlVTnVpaS9BVW9UN1pTQTNldEJZXG5VNmFwTXpwbmpReTBxMU9BeVhDZUFhZUNwRWRuTHpzU3IrZFFQVTJRTGNuUUh4V1RIUmNOZmhGK1JNek9QbGo5XG40OUZsWnVGQU1vdmhjY3RtOUE2Q2xoTHZyVk5ydHJybDVxSkJ6U1VDZ1lBb3FseUZLRGxuaWJnTnFjV0Q4N3J6XG5xVEVBZFprWENQNWJMSGQyUzI0V2tLTFZFay9kUnVrZWhNZ0RJT0ZGYjhLSmRMeldaMWZaWXpsZW5TdzlBR3Z2XG5PUU5udktUOVoxaTRkbDZuZ1pGQ3E2UVZ4OSttTUNsUHVNbUd6aHgwNzFJam1venRXVVNyTGhwNFVNT0hRMHkxXG55OVRWbWRTMVh2TUlVSzNyQldSSDJnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJzcGlubmFrZXItZ2NzLWFjY291bnRAYXJpa2tmaXIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEzNTAyNDIyMTE3MTM0NTQwMzUxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zcGlubmFrZXItZ2NzLWFjY291bnQlNDBhcmlra2Zpci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
  spinnaker-pubsub-account.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYXJpa2tmaXIiLAogICJwcml2YXRlX2tleV9pZCI6ICI1Y2I5MTZkMWVlYmYwOGVkNWU2ZTdhMWI5YThkOGM0ZjAxYzQ3ZWMzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUNJTVhNb0dYRTRETEtpXG5yY2p5QUdoanB6RGxhRmltYy9NRVdCc3dxNTNnVzlrbEhIb0tmYWs4ZXdvQk9YV09wd0gveFBlWmc3VkJpRXdrXG5KcFNSbkYyNGNmM1psbUQ5TmxLMjk2ZDh5T0l5NGJGTjRaZ0NYeHFIbTJub1NQVkUxNFdOUTJZRW5kMi82b0piXG5vcGdNazE3T2UwL3VTZDBXOG1oVktlSERYL01aWi9FUm82N0gxdXN6b21HNjl5dlhqZTdDVGhqZ0FQbFhGVnYxXG41Q3pRSEVpcFI0RmJsdjVUOFNTTGVMbnRTMzdubEJqa0lYbmt5bWZoS0RJZSt2NE1aeWE4ckQ4dzA5U2llVisxXG4xSDFnVXV6eFRHUUxjTDMwbmFXQTNQSjU1TVJJY0pKSzd6bFU5elhzV1ZiU1pFeitMVUlHVGV4WE1iamE3YlpIXG5DSjVDUHN5dEFnTUJBQUVDZ2dFQUR1OHhQQVB5Tk4yN2x2Z3NrVkQzSVhwYmM4U0orQks5NHN1UWk3azk4alRRXG5MbkFkZDlvSXZVK1dyTVN5dmVaVlkwa2poNHQ0VEV2WVlaeHpiVFl5MXI5MVFTOXF5a2x6TDRvZnJTRFFJUms3XG5tcGt5MUl1K09vR1J6djExRzh2d1lxbXgzYTY3K3NnSjdHZDdlZUdOSTJKRlJSR0hjM1U0ZUtKRGxldUhHbEZ4XG5HQ1E0MGplZkZRS3hxajRzdWcxTGVSTWFveUwyTUYrVVF0Rkxva3daQ1RTTnBuenB3U1FtblREMFF2TTJmV1FXXG5hdGtxdHNnUmRtMlpvcUFGMmN0TmdCQkRvNUx6ZUlETE5Sd1g2SnlocTNqbUl6M2ZFd0t5bEpBRGcvNGtxWEhjXG41WnFxa0xjbERBNGErMFdkdUZtVHVORXhYT2JBRVVENSt0bGh2SW9wVVFLQmdRQy8wTjRXRXRSeEtqYmVRZE94XG5SQ0M1NlNjMkk0VTdnWnEwajdOekliTlFYRHQ1WlBZM2V0clgyZDA4VHpjcWx1elNockJsY241cmNSMmg5eGhjXG4wS2p4QmN1aDhYZ0I0c1hES1Ztb0ZwOHZLdXluMHY1c2xwdDBkaG1NU0FpalU0TUkzaEs1U2JaN3N3Q2tpYnNtXG41NzJIL2lsbjkrTStIbmRUUUNoUW9XbzNCUUtCZ1FDMXcrTHV6dlpzK2Z4VWVNVXdBcDc0VUE1NkVibGYyYWU2XG5ySzlZditSeFkyb21ocUVObDVBc0gyMjhSOWF2NE92UnI3RFM1emVWWm5CVmVrOUw4VEtoaDdqSUFBVFpoTXBtXG4vblhxcDJ4Tzk4ZWJLRzhadjBRRXQvU3VFQWZpb2QrZE52SFUrTXNCQ0x2K0RwTTBxSXg0cXlkT21OVW1uU1lhXG5nWWRqQmJMZmlRS0JnQ3kwVnk0NTBUMVdvMWNGYkhzQjc4YWthamtaNmpGR01YSW5rNkVmbDVVQkNmTnU3bHRiXG56S2xGNDJQczZtU0lyRVVja3Z2eHhUanhNZ0RQZitRUjFXM205ZUNXVUd2UUdGczF4ZW1BN0RTb0FtUFNydTFMXG41SXN1QXlKSW40ckJLZWJsS3VQNEpBbU1YSGY4aVp1MW90eVJCY0Z2YW96TnVPMjBKREUyalhTcEFvR0FEa0xlXG5UVXBqdjAwbDVTTE1wZVd1djJEWW9lOCtFaTByb2RQbXRobm9QSlZHUU51VFMxTzI5aDlKSnRxa0Y0eVlOQTJLXG4zQ0ZVRlI3Q2RaSnhJazQ4WUx3YlhXWFMrNVlWbzFzWHVWK0ZlZlNxN3B1UGkvK2J3SnNHVVpua1pIMjY0OFRwXG4ySUhrdTZJSnpmY3F5WmpuM0pmaEw2T0NKZE55cCtXOXo2RWsxYkVDZ1lFQW94UGtZWnRGajZXRU94UE9UUjF3XG50bXI5elhQQmxmblVwUm94UDFWSFBtR2Nhc1h1R2NrNlRZN0dXQytzaUJJTnAyRWxLb211ZWpTUHd2T1pTN1R6XG5BZ1hSdUdvUEt4T3dCc3doNlpsUi82c3VOWlczR0tlanFnZ1BKRXFIREgzbDNsUmV6TUlZS2pTOU1YT01qRFp3XG4zbzdJNGU1RlZScFVsTnpRQlozbUNwYz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJzcGlubmFrZXItcHVic3ViLWFjY291bnRAYXJpa2tmaXIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA4MTgxNTg2NDQ1NzE5MjAyOTI3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zcGlubmFrZXItcHVic3ViLWFjY291bnQlNDBhcmlra2Zpci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: spinnaker
  name: spinnaker
  labels:
    app: spinnaker
spec:
  secretName: spinnaker-crt
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: spinnaker.kfirs.com
  dnsNames:
    - spinnaker.kfirs.com
    - gate.spinnaker.kfirs.com
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - spinnaker.kfirs.com
          - gate.spinnaker.kfirs.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: spinnaker
  name: spinnaker
  labels:
    app: spinnaker
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/whitelist-source-range: "${WHITELISTED_IP_CIDRS}"
spec:
  rules:
    - host: spinnaker.kfirs.com
      http:
        paths:
          - backend:
              serviceName: spin-deck
              servicePort: 9000
    - host: gate.spinnaker.kfirs.com
      http:
        paths:
          - backend:
              serviceName: spin-gate
              servicePort: 8084
  tls:
    - hosts:
        - spinnaker.kfirs.com
        - gate.spinnaker.kfirs.com
      secretName: spinnaker-crt
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: spinnaker
  name: config
  labels:
    app: spinnaker
data:
  setup.sh: |
    #!/usr/bin/env bash

    set -eu -o pipefail

    # setup "~/.kube"
    [[ ! -d ~/.hal/.kube ]] && mkdir -pv ~/.hal/.kube
    [[ ! -L ~/.kube ]] && (rm -rfv ~/.kube; ln -s ~/.hal/.kube ~/.kube)
    kubectl config set-cluster devops --server=https://kubernetes.default --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    kubectl config set-credentials serviceaccount --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    kubectl config set-context devops --cluster=devops --user=serviceaccount
    kubectl config use-context devops

    # setup ~/.bashrc
    grep -e "^alias ll" /home/spinnaker/.bashrc > /dev/null || echo "alias ll='ls -l'" >> /home/spinnaker/.bashrc
    grep -e "^alias la" /home/spinnaker/.bashrc > /dev/null || echo "alias la='ls -la'" >> /home/spinnaker/.bashrc
    grep -e "^source <(hal --print-bash-completion)" /home/spinnaker/.bashrc > /dev/null || echo "source <(hal --print-bash-completion)" >> /home/spinnaker/.bashrc

  configure.sh: |
    #!/usr/bin/env bash

    set -eu -o pipefail

    PROJECT=arikkfir
    BUCKET=arikkfir-spinnaker
    GCR_SA_KEY_FILE=/home/spinnaker/secrets/spinnaker-gcr-account.json
    GCS_SA_KEY_FILE=/home/spinnaker/secrets/spinnaker-gcs-account.json
    PUBSUB_SA_KEY_FILE=/home/spinnaker/secrets/spinnaker-pubsub-account.json
    JENKINS_PWD=$(cat /home/spinnaker/secrets/jenkins-password)
    VERSION=1.12.7

    # public URLs
    hal config security api edit --override-base-url https://gate.spinnaker.kfirs.com
    hal config security ui edit --override-base-url https://spinnaker.kfirs.com

    # cloud providers
    hal config provider kubernetes enable
    hal config provider kubernetes account add k8s-devops --provider-version v2 --context devops

    # storage
    hal config storage gcs edit --project ${PROJECT} \
        --bucket ${BUCKET} \
        --json-path ${GCS_SA_KEY_FILE}
    hal config storage edit --type gcs

    # artifacts
    hal config features edit --artifacts true
    hal config artifact gcs account add gcs --json-path ${GCS_SA_KEY_FILE}
    hal config artifact gcs enable

    # pubsub
    hal config pubsub google enable
    hal config pubsub google subscription add google-pubsub-gcr \
        --subscription-name spinnaker-gcr \
        --json-path ${PUBSUB_SA_KEY_FILE} \
        --project ${PROJECT} \
        --message-format GCR
    hal config pubsub google subscription add google-pubsub-cloud-builds \
        --subscription-name spinnaker-cloud-builds \
        --json-path ${PUBSUB_SA_KEY_FILE} \
        --project ${PROJECT} \
        --message-format GCB

    # jenkins
    hal config ci jenkins enable
    echo ${JENKINS_PWD} | hal config ci jenkins master add master \
        --address http://master.jenkins \
        --username spinnaker \
        --password

    # deployment
    hal config deploy edit --type distributed --account-name k8s-devops
    hal config version edit --version ${VERSION}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spinnaker
  name: halyard
  labels:
    app: spinnaker
    component: halyard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker
      component: halyard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spinnaker
        component: halyard
    spec:
      serviceAccountName: spinnaker
      initContainers:
        - name: init-chown-data
          image: busybox:latest
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 64Mi
          command: ["chown", "-R", "1000:1000", "/data"]
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
        - name: halyard
          image: gcr.io/spinnaker-marketplace/halyard:1.17.0
          lifecycle:
            postStart:
              exec:
                command: [bash, -c, 'bash /home/spinnaker/bin/setup.sh']
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /home/spinnaker/bin
              readOnly: true
            - name: secrets
              mountPath: /home/spinnaker/secrets
              readOnly: true
            - name: storage
              mountPath: /home/spinnaker/.hal
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: config
            optional: false
        - name: secrets
          secret:
            secretName: secrets
            optional: false
        - name: storage
          persistentVolumeClaim:
            claimName: halyard
            readOnly: false
---
