apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgArP9MZNLNo9D8R7QlpsmIZ7BxrW59Wy/JUSfMtU7YPzcV90PlEO65QZ0dClFzCOpN4ziYGhEpRTe6SUE7sLPzgoyPwWpu2OjWQZkRd++28SsiYwa+ru8FJR3EuEVXI+qw8SnC+Fp1ZarGGoWI0QBR6moi+SPdIQpY0f8C6lsDwC0ZPGIbS4Vc0FjjSPO/BUvCYckYoyOSUjeW5DrX0VNuiAC0JPw0IOUIJBpjaejtypyjF8xjjfBFccBkmKyZT+ySMhBfxHHwYcWvzxDdzhhm3uTPrRe2soz8gQkspYeMRICI+OIMEDsmhM6gAbm365GzoekpSdgY9gNcE6kIGTnAwwqC+UTB5vKmjhRY787Ey5nVWVIQMzJZ4p+HsIFyJUI5G5iPwY4V60PVmdTg7QKVBaRp7dHU12pmYUsjUbWl9aKloX+tkeEZo3ksC/xPbm9IPqE7Rf9REiTKCltP5jdicRd1FyJeCNPmSzmfS9I3llL8LgNUKumjX2pJ2rewCJi6MDE6u30saBT1ZFGOFuisZEo2ENEQsHAVQ8exyTbk2D0FF14fZ6qhrdpKadUWevMbLitarSjnzGjl0sTntafKyfAjT/TKZbLnPBIHhXaoquTujIg9FoFjbR8y9R3gEsL3buV2cnVH91i8BokbPFpj6ZAm94dQrDB4z5uf0/h9DtKdHC5jAn4G2uh9vwnQiq60/7QU1ekQThcTQhH9fUDDdInqPJSOBXCvk1Iu51gtiDaFo4hWL6/lQ
  template:
    metadata:
      name: cloudflare-api-token-secret
