apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      version: '9.15.2'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 1m
  releaseName: traefik
  postRenderers:
    - kustomize:
        patchesJson6902:
          - patch:
              - op: replace
                path: /spec/loadBalancerIP
                value: "35.198.167.23"
            target:
              group: ""
              version: v1
              kind: Service
              name: traefik
  values:
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    providers:
      kubernetesIngress:
        enabled: false
    logs:
      general:
        level: ERROR
        format: json
      access:
        enabled: true
        format: json
        fields:
          general:
            defaultmode: keep
          headers:
            defaultmode: true
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerSourceRanges:
        - "46.116.50.28/32"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 60
        - type: Resource
          resource:
            name: memory
            targetAverageUtilization: 60
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
