name: Create PR on branch push
on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash -exuo pipefail {0}

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  create-pr:
    name: Create PR
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: |-
          gh pr list
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          base: main
#          branch: ${{ github.ref }}
#          body: Auto-created Pull Request
#          commit-message: Auto Pull Request
#          title: Your desired title
