name: Deploy

on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - "*.tf"
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  GCP_SERVICE_ACCOUNT: infrastructure@arikkfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  GCP_CLI_VERSION: 443.0.0
  TERRAFORM_VERSION: 1.5.5
  TF_IN_AUTOMATION: true
  TF_VAR_gcp_project_id: arikkfir
  TF_VAR_gcp_region: me-west1

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  plan-terraform:
    name: Plan Terraform
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff
      - run: terraform init -input=false
      - run: terraform plan -input=false -lock-timeout=20m -out tfplan
      - run: tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 1

  apply-terraform:
    name: Apply Terraform
    needs: plan-terraform
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    environment: production
    permissions:
      id-token: write
    outputs:
      gcp_region: ${{ steps.out.outputs.gcp_region }}
      main_gke_cluster_name: ${{ steps.out.outputs.main_gke_cluster_name }}
      main_gke_cluster_location: ${{ steps.out.outputs.main_gke_cluster_location }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - run: tar -x -j -v -f tfplan.tar.bz2
      - run: terraform apply -input=false -lock-timeout=120s -auto-approve tfplan
      - id: out
        name: Outputs
        run: |
          echo "gcp_region=$(terraform output -raw gcp_region)" >> "$GITHUB_OUTPUT"
          echo "main_gke_cluster_name=$(terraform output -raw main-gke-cluster-name)" >> "$GITHUB_OUTPUT"
          echo "main_gke_cluster_location=$(terraform output -raw main-gke-cluster-location)" >> "$GITHUB_OUTPUT"

  sync-delivery-repository:
    name: Sync "delivery" repository
    needs: apply-terraform
    uses: arikkfir/delivery/.github/workflows/sync-gke-cluster-info.yml@main
    with:
      gke_cluster_name: ${{ needs.apply-terraform.outputs.main_gke_cluster_name }}
      gke_cluster_location: ${{ needs.apply-terraform.outputs.main_gke_cluster_location }}
      gke_ingress_region: ${{ needs.apply-terraform.outputs.gcp_region }}
    secrets: inherit

  apply-fluxcd:
    name: Apply FluxCD
    needs: [apply-terraform, sync-delivery-repository]
    uses: arikkfir/delivery/.github/workflows/apply-fluxcd.yml@main
    with:
      gke_cluster_name: ${{ needs.apply-terraform.outputs.main_gke_cluster_name }}
      gke_cluster_location: ${{ needs.apply-terraform.outputs.main_gke_cluster_location }}
    secrets: inherit
